#!/usr/bin/env python3
"""Step 1. Solved VHAP chunks -> FLAME vertex sequences on disk.

    ~/miniconda3/envs/vhap/bin/python rigfit/harvest_flame.py --per-video 12 --stride 2

Runs in the `vhap` env, the only one carrying the FLAME model. Everything downstream
runs in `stavatar`, which has the MetaHuman rig, so the two halves have to meet on disk.

WHAT IS WRITTEN, PER CHUNK
    verts    [T, 5023, 3]   posed, expression + articulation only
    neutral  [5023, 3]      the same identity with expression and articulation zeroed

TWO SOURCES, AND THE DIFFERENCE MATTERS
    --source shared   every chunk solved against one locked identity PER RECORDING.

                      CORRECTED 2026-09-13. This used to claim the 300 shape coefficients
                      and the per-vertex offset were byte-identical "across all 168 runs
                      and all three videos". They are byte-identical WITHIN a recording
                      and differ between recordings: shape coefficients by up to 1.90,
                      static_offset by up to 0.015 cm. The check was evidently run within
                      one take and the conclusion generalised to three.

                      The geometric consequence is small -- the neutral differs by
                      0.14-0.24 mm at its worst vertex and 0.01 mm on average, under the
                      0.70 mm noise floor, and it accounts for ~1% of the between-take
                      drift in the expression measures. But "one identity across all
                      three recordings" is not a fact we have, and anything resting on it
                      was resting on something unchecked.
    --source chunks   every chunk solved with its own identity. Kept because comparing
                      the two MEASURES the drift: 0.2 mm mean vertex displacement.

    The neutral is still written per chunk. Under --source shared it comes out the same
    every time, which is the point: it makes that fact checkable downstream rather than
    assumed.

    The synthesised teeth slab (vertices 5023..5142) is dropped. It is not observed, it
    is generated by VHAP to fill the mouth, and it would otherwise be scored as if it
    were tracked geometry.
"""
import argparse
import json
import os
import pathlib
import sys

import numpy as np
import torch

VHAP = (pathlib.Path(__file__).resolve().parents[1] / "vhap")
N_FLAME = 5023
OUT = pathlib.Path(__file__).resolve().parent / "cache/flame"


def pick(per_video, videos=None, source="shared"):
    """Evenly spaced solved chunks from each video, newest run per chunk."""
    runs = {}
    for p in sorted((VHAP / "output" / source).glob("*/*/tracked_flame_params_30.npz")):
        runs[p.parent.parent.name] = p              # sorted -> newest run wins
    by_video = {}
    for name, p in runs.items():
        by_video.setdefault(name.rsplit("__c", 1)[0], []).append((name, p))
    out = []
    for vid, items in sorted(by_video.items()):
        if videos and vid not in videos:
            continue
        items.sort()
        idx = np.linspace(0, len(items) - 1, min(per_video, len(items))).round().astype(int)
        out += [(vid, *items[i]) for i in sorted(set(idx.tolist()))]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-video", type=int, default=12)
    ap.add_argument("--stride", type=int, default=2)
    ap.add_argument("--profile", required=True,
                    help="recipes/audio-to-mesh/profiles/<name>.py: whose recordings, and "
                         "where they go. output/shared holds every creator's chunks, so "
                         "harvesting it whole mixes people into one corpus")
    ap.add_argument("--videos", nargs="*", default=None,
                    help="default: the profile's RECORDINGS")
    ap.add_argument("--source", default="shared", choices=("shared", "chunks"))
    ap.add_argument("--out", default=None,
                    help="default: the profile's FLAME_FULL at --stride 1, FLAME_SHARED "
                         "otherwise")
    a = ap.parse_args()
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent / "recipes/audio-to-mesh/tools"))
    from _profile import load
    p = load(a.profile)
    a.videos = a.videos or list(p.RECORDINGS)
    if not a.out:
        base = p.FLAME_FULL if a.stride == 1 else p.FLAME_SHARED
        a.out = str(base if a.source == "shared"
                    else base.parent / base.name.replace("_full", "_chunks").replace("_shared", "_chunks"))

    sel = pick(a.per_video, a.videos, a.source)
    print(f"{len(sel)} chunks from {len(set(v for v, _, _ in sel))} videos")

    sys.path.insert(0, str(VHAP))
    os.chdir(VHAP)                                  # FlameHead hardcodes asset/ paths
    from vhap.model.flame import FlameHead
    flame = FlameHead(300, 100, add_teeth=True, remove_lip_inside=False)

    outdir = pathlib.Path(a.out or (OUT.parent / f'flame_{a.source}'))
    outdir.mkdir(parents=True, exist_ok=True)
    index = []
    for n, (vid, name, p) in enumerate(sel):
        dst = outdir / f"{name}.npz"
        z = np.load(p)
        assert z["static_offset"].shape[1] == flame.v_template.shape[0], \
            f"{name}: topology mismatch, add_teeth flag differs from this run"
        T = z["expr"].shape[0]
        keep = np.arange(0, T, a.stride)
        t = lambda x: torch.as_tensor(np.asarray(x), dtype=torch.float32)
        so = t(z["static_offset"])
        zero3 = torch.zeros(1, 3)
        with torch.no_grad():
            # the chunk's own rest face: identity only, nothing articulated
            neutral = flame(shape=t(z["shape"])[None], expr=torch.zeros(1, 100),
                            rotation=zero3, neck=zero3, jaw=zero3,
                            eyes=torch.zeros(1, 6), translation=zero3,
                            static_offset=so)[0][0, :N_FLAME].numpy()
            V = np.empty((len(keep), N_FLAME, 3), np.float32)
            for j, i in enumerate(keep):
                V[j] = flame(shape=t(z["shape"])[None], expr=t(z["expr"][i])[None],
                             rotation=zero3, neck=t(z["neck_pose"][i])[None],
                             jaw=t(z["jaw_pose"][i])[None], eyes=t(z["eyes_pose"][i])[None],
                             translation=zero3, static_offset=so)[0][0, :N_FLAME].numpy()
        np.savez_compressed(dst, verts=V, neutral=neutral.astype(np.float32),
                            shape=np.asarray(z["shape"]), frames=keep, video=vid)
        index.append({"chunk": name, "video": vid, "frames": int(len(keep)),
                      "file": str(dst), "source": a.source})
        print(f"  [{n+1}/{len(sel)}] {name}  {len(keep)} frames", flush=True)

    (outdir / "index.json").write_text(json.dumps(index, indent=1))
    print("wrote", outdir / "index.json")


if __name__ == "__main__":
    main()
